name: Docker

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"

env:
  IMAGE_NAME: roon

jobs:
  push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/jmmaloney4/roon:latest
            docker.io/jmmaloney4/roon:${{github.run_number}}
            ghcr.io/jmmaloney4/roon:latest
            ghcr.io/jmmaloney4/roon:${{github.run_number}}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
